# ./7-bitnami-postgres/Chart.yaml
apiVersion: v2
name: demo-express-app
description: Demo Node + Express application
type: application
# Bumping patch version of the chart.
version: "1.0.1"
appVersion: "1.0.0"
