# ./8-values/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-express-app-v1
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-express-app
      app.kubernetes.io/version: "1"

  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-express-app
        app.kubernetes.io/version: "1"
    spec:
      containers:
        - name: demo-express-app-v1
          image: demo-express-app:1
          imagePullPolicy: Never
          ports:
            - name: http-web-svc
              containerPort: {{.Values.demoExpressApp.port}}
          env:
            - name: PORT
              value: "{{.Values.demoExpressApp.port}}"
            - name: DATABASE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: demo-express-app-secret
                  key: databaseConnectionString
