# ./8-values/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: demo-express-app-secret
stringData:
  databaseConnectionString:
    {{template "demoExpressApp.databaseConnectionString" .}}
