apiVersion: v1
kind: Pod
metadata:
  name: demo-express-app-v1
  # It is considered a best practice to add these name and version labels to
  # resources as it makes working with these resources easier down the line.
  labels:
    app.kubernetes.io/name: demo-express-app
    app.kubernetes.io/version: "1"
spec:
  containers:
    - name: demo-express-app
      image: demo-express-app:1
      # We never want to pull this image because it's only available locally.
      # For remote images you will want to remove this or change it's value.
      imagePullPolicy: Never
    # We could declare multiple containers here.
