FROM node:16 as build

WORKDIR /app

COPY package*.json ./
RUN npm clean-install

COPY tsconfig.json .
COPY src src

RUN npm run build

FROM node:16

WORKDIR /app

COPY --from=build /app/package*.json ./
COPY --from=build /app/node_modules node_modules
COPY --from=build /app/dist dist

CMD ["node", "dist/app.js"]
